### ISSUE TITLE
leaflet-pegman is not working on chrome

### ISSUE THREAD

**Issue by prernamedhe** [Raruto/leaflet-pegman#2]

**Comment by Raruto** [comment]
It's something related to the [interact.js](https://github.com/Raruto/leaflet-pegman/blob/1e494b31a8d8f8323dbc3a2526ec3ad380e8e20c/leaflet-pegman.js#L495) events.

Some tests should be done with its latest available version, can you give me a hand?

**PS** it only happens on the desktop version, right?

**Comment by prernamedhe** [comment]
yes it happens on the desktop only ...so can you please give me proper
solution for that

**Comment by Raruto** [comment]
In version **0.0.9** I slightly modified the way the _"touchstart"_ event is handled.

Let me know if it works well now...

_Greetings,
Raruto_

**Comment by prernamedhe** [comment]
version  0.0.9 ?

**Comment by prernamedhe** [comment]
Thank you very much @Raruto ...
version 0.0.9 is working perfectly...thanks for your help
