### ISSUE TITLE
Event listeners still working after remove

### ISSUE THREAD

**Issue by nikopeikrishvili** [Raruto/leaflet-pegman#4]
Event listeners still working even after removing control:
```javascript
pegmanControl.remove()
```

I'm getting an error on mouse move :
```
Uncaught TypeError: Cannot read property 'getZoom' of null
    at i._setMouseCursor (leaflet-pegman.js:434)
```
My goal is to show pegman control after zoom level 15 but hide it before

P.S thanks for plugin

**Comment by Raruto** [comment]
Hi Niko,
it should be ok from version **0.1.4**.

_Happy Coding,
Raruto_
