### ISSUE TITLE
Pegman lines in a wrong place

### ISSUE THREAD

**Issue by nikopeikrishvili** [Raruto/leaflet-pegman#5]
I have a problem with Pegman, lines loaded in the wrong place, any idea why it's happening? or how can I debug it?
![Screen Shot 2020-10-17 at 13 58 18](https://user-images.githubusercontent.com/10278664/96334320-e5ab5000-1080-11eb-92ca-1d6c542e5f23.png)

**Comment by Raruto** [comment]
Hi niko,
underneath this library uses the: https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant in order to display streetview data. i don't know how you achieve to load google maps tiles, but it could be a crs or tile size problem.

**Comment by nikopeikrishvili** [comment]
Thank you, you have hardcoded the GoogleMutant version in code and the library is using this version even if I load another via npm, how can I override your version?

**Comment by Raruto** [comment]
> you have hardcoded the GoogleMutant version in code and the library is using this version even if I load another via npm

Strange, as you can see [here](https://github.com/Raruto/leaflet-pegman/blob/ed6db685e725cdc8a946c59237aac176f02242de/leaflet-pegman.js#L540), there is already a check to make sure that library doesn't load twice (pay attention to the order of your imports).

> how can I override your version?

You can do such a thing:

```js
L.Control.Pegman.include({
  __mutantURL: 'https://unpkg.com/leaflet.gridlayer.googlemutant@0.10.0/Leaflet.GoogleMutant.js'
});

var pegmanControl = new L.Control.Pegman({ ... });
```

**Comment by nikopeikrishvili** [comment]
For other users who will be faced with the same issue its a CSS issue if the map element has `text-align: center` property
