### ISSUE TITLE
Add a new feature to the offer: PanoViewer 

### ISSUE THREAD

**Issue by velocat** [Raruto/leaflet-pegman#6]
The desired plugin. 
I would like to use it, but I don't have the ability to display the panorama next to the map from the side or from the bottom/top, this is how it is implemented here:

![pano](https://user-images.githubusercontent.com/534853/99225420-181fa880-27f9-11eb-9cbb-dcc1b917ff06.PNG)

or:

![pano21](https://user-images.githubusercontent.com/534853/99225423-1950d580-27f9-11eb-8d18-bed8082e7108.PNG)

1. Dragging a size
2. Changes the position

Code for this example: https://github.com/velocat/nakarte/blob/master/src/lib/leaflet.control.panoramas/index.js

**Comment by Raruto** [comment]
https://github.com/Raruto/leaflet-pegman/blob/ed6db685e725cdc8a946c59237aac176f02242de/leaflet-pegman.js#L81

**Comment by Raruto** [comment]
Hi velocat,
congratulations for the project.

By chance, are you looking for the `panodiv` option?

https://github.com/Raruto/leaflet-pegman/blob/ed6db685e725cdc8a946c59237aac176f02242de/leaflet-pegman.js#L81

https://github.com/Raruto/leaflet-pegman/blob/ed6db685e725cdc8a946c59237aac176f02242de/leaflet-pegman.js#L417

_Have a nice day,
Raruto_

**Comment by velocat** [comment]
> congratulations for the project.

This is not my project, I'm creating another one, and in this one I showed the implementation )))

> By chance, are you looking for the `panodiv` option?

Partially Yes, it helped.
But you probably wrote this plugin without counting on this mode? ))

1. Pegman remains stationary in this mode, no matter where I move on the panorama.
2. It is always pointed in one direction, no matter how I turn the view.
3. It is not linked to the panorama lines, so you can always put it in the place of the map where there are no panoramas, and if you put it the first time, the panorama window will not open, but the second or more - the panorama remains in its old place, and it would be better if it moved to the nearest point.

![pano3](https://user-images.githubusercontent.com/534853/99249135-a5272980-281a-11eb-927d-a5fefa944a9b.PNG)


Here is an example: In the screenshot, I went far away from the place where I put the little man on panoramas, but he stands still.
In panoramas, I look to the North, and the marker man always looks to the Southeast

Well, the main thing I would like is to place this block in the map block, with the ability to zoom and move. If you are interested, see how this is implemented on that site: https://nakarte.me

And another thing: my google API is loaded by the user, if necessary, that is, it turns out that the script with the key is already loaded, and this plugin tries to load it again. I can of course remove this line myself, but I think it would be more correct

**Comment by Raruto** [comment]
> you probably wrote this plugin without counting on this mode? ))

That's right, if you are interested in implementing these functions you can start from the following hooks:

- [position_changed](https://github.com/velocat/nakarte/blob/f38b5942bad8c7ce59f42d557ec5497bfea75ac2/src/lib/leaflet.control.panoramas/lib/google/index.js#L42)

- [pov_changed](https://github.com/velocat/nakarte/blob/f38b5942bad8c7ce59f42d557ec5497bfea75ac2/src/lib/leaflet.control.panoramas/lib/google/index.js#L43)

- [change](https://github.com/velocat/nakarte/blob/f38b5942bad8c7ce59f42d557ec5497bfea75ac2/src/lib/leaflet.control.panoramas/lib/google/index.js#L61)

and finally the [onPanoramaChangeView](https://github.com/velocat/nakarte/blob/f38b5942bad8c7ce59f42d557ec5497bfea75ac2/src/lib/leaflet.control.panoramas/index.js#L348) callback allows you to modify the leaflet marker (latlng / heading).

**Comment by velocat** [comment]
Pull: https://github.com/Raruto/leaflet-pegman/pull/7  :))

![Pegman](https://user-images.githubusercontent.com/534853/99373337-5341da80-28d2-11eb-92fe-bb3a39702080.PNG)
