### ISSUE TITLE
Feature Request: Launch street view without mouse action

### ISSUE THREAD

**Issue by Hugo01** [Raruto/leaflet-pegman#8]
Hello
First of all thanks for your effort, lib works wonderfull
I was wondering if somehow it was possible to create a method that you could call street view only passing a {lat: x, lng: y} without having to point on the map

Something like this:

```js
const pegmanControl = new L.Control.Pegman({
  position: 'bottomright'
  theme: 'leaflet-pegman-v3-small'
})

pegmanControl.startView({lat:x, lng:y})
```

**Comment by Raruto** [comment]
If I'm not mistaken, this should be the function you are looking for:

```js
pegmanControl.findStreetViewData(lat, lng);
```

_Have a nice day,
Raruto_
